/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.robosim.physmod.slnDF.validation;

import org.eclipse.xtext.validation.Check;
import circus.robocalc.robosim.physmod.slnDF.slnDF.FunctionForLoop;
import circus.robocalc.robosim.physmod.slnDF.slnDF.RowLiteral;
import circus.robocalc.robosim.physmod.slnDF.slnDF.VectorOrMatrix;
import circus.robocalc.robosim.physmod.slnDF.slnDF.ForLoop;
import circus.robocalc.robosim.physmod.slnDF.slnDF.Function;
import circus.robocalc.robosim.physmod.slnDF.slnDF.ParameterDeclaration;
import circus.robocalc.robosim.physmod.slnDF.slnDF.SlnDFPackage;
import circus.robocalc.robosim.physmod.slnDF.slnDF.Variable;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SlnDFValidator extends AbstractSlnDFValidator {
	
	// in circus.robocalc.robosim.physmod.slnDF.validation.SlnDFValidator (or similar)
	@Check
	public void noInitInFunctionLoop(FunctionForLoop loop) {
		Variable v = loop.getVariable();
		if (v != null && v.getInitialValue() != null) {
			error(
				"Loop variable in a function body must not have an initial value (use range(...) for the start).",
				v,
				SlnDFPackage.Literals.VARIABLE__INITIAL_VALUE
			);
		}
	}

    @Check
    public void nonEmptyRowLiterals(VectorOrMatrix vm) {
        if (vm == null || vm.getRows() == null) return;
        for (circus.robocalc.robosim.physmod.slnDF.slnDF.Expression expr : vm.getRows()) {
            if (expr instanceof RowLiteral) {
                RowLiteral row = (RowLiteral) expr;
                if (row.getElements() == null || row.getElements().isEmpty()) {
                    error("Row literals must have at least one element.", row, SlnDFPackage.Literals.ROW_LITERAL__ELEMENTS);
                }
            }
        }
    }

	@Check
	public void noInitInComputationForLoop(ForLoop loop) {
		Variable v = loop.getElementVariable();
		if (v != null && v.getInitialValue() != null) {
			error(
				"Loop variable must not have an initial value (use range(...) for the start).",
				v,
				SlnDFPackage.Literals.VARIABLE__INITIAL_VALUE
			);
		}
	}

//	@Check
//\tpublic void noInitInFunctionParameters(Function function) {
//\t	if (function.getParameters() == null) {
//\t		return;
//\t	}
//\t	for (Variable param : function.getParameters()) {
//\t		if (param.getInitialValue() != null) {
//\t			error(
//\t				"Function parameters must not have an initial value.",
//\t				param,
//\t				SlnDFPackage.Literals.VARIABLE__INITIAL_VALUE
//\t			);
//\t		}
//\t	}
//\t}
//
//	@Check
//\tpublic void noInitInProcedureParameters(ParameterDeclaration decl) {
//\t	Variable v = decl.getVariable();
//\t	if (v != null && v.getInitialValue() != null) {
//\t		error(
//\t			"Procedure parameters must not have an initial value.",
//\t			v,
//\t			SlnDFPackage.Literals.VARIABLE__INITIAL_VALUE
//\t		);
//\t	}
//\t}

}
