/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import circus.robocalc.robosim.physmod.slnRef.SlnRefRuntimeModule;
import circus.robocalc.robosim.physmod.slnRef.SlnRefStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SlnRefIdeSetup extends SlnRefStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SlnRefRuntimeModule(), new SlnRefIdeModule()));
	}
	
}
