/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef.ide;


/**
 * Use this class to register ide components.
 */
public class SlnRefIdeModule extends AbstractSlnRefIdeModule {
}
