/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SlnRefRuntimeModule extends AbstractSlnRefRuntimeModule {
}
