/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SlnRefStandaloneSetup extends SlnRefStandaloneSetupGenerated {

	public static void doSetup() {
		new SlnRefStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
