/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.robosim.physmod.slnDF.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SlnDFUiModule extends AbstractSlnDFUiModule {

	public SlnDFUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
