source.. = src/,\
           xtend-gen/
output.. = bin/
bin.includes = .,\
               META-INF/,\
               lib/
bin.excludes = **/*.xtend
additional.bundles = org.eclipse.xtext.xbase,\
                     org.eclipse.xtext,\
                     org.eclipse.xtend.lib,\
                     org.eclipse.emf.ecore,\
                     org.eclipse.emf.common,\
                     org.antlr.runtime
