package circus.robocalc.robosim.physmod.generator.sourceCodeGen.tests;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

import org.eclipse.xtext.generator.InMemoryFileSystemAccess;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import com.google.inject.Inject;

import circus.robocalc.robosim.physmod.generator.sourceCodeGen.SolutionRefGenerator;
import circus.robocalc.robosim.physmod.generator.sourceCodeGen.tests.SlnRefInjectorProvider;
import circus.robocalc.robosim.physmod.slnRef.slnRef.SlnRefs;

/**
 * T5 integration test: feed T4 slnRef output and ensure T5 generates Solution DSL and C++.
 */
@ExtendWith(InjectionExtension.class)
@InjectWith(SlnRefInjectorProvider.class)
public class TestSKO_T5Integration_LibRefs {

    @Inject
    private ParseHelper<SlnRefs> slnRefParseHelper;
    private static final String TESTDATA_PROJECT_PATH =
        "../../physmod-testdata/circus.robocalc.robosim.physmod.testdata/testdata/integration/T5/SKO/";

    private Path integrationRoot() {
        return Paths.get("").toAbsolutePath().resolve("tests").resolve("integrationTests").resolve("SKO");
    }

    private Path testdataRoot() {
        return Paths.get("").toAbsolutePath().resolve(TESTDATA_PROJECT_PATH);
    }

    @Test
    public void testGenerateFromT4SlnRef_SKO_LibRefs() throws Exception {
        // Input: T4 slnRef copied into T5 tests
        Path input = testdataRoot().resolve("default").resolve("input").resolve("SimpleArmSerial.slnRef");
        if (!Files.exists(input)) {
            input = testdataRoot().resolve("integrated").resolve("input").resolve("SimpleArmSerial.slnRef");
        }
        assertTrue(Files.exists(input), "Missing input slnRef in default or integrated input directory");

        String slnRefText = Files.readString(input);

        // Parse slnRef using injected parser
        SlnRefs slnRefs = slnRefParseHelper.parse(slnRefText);
        assertNotNull(slnRefs, "Failed to parse SlnRefs");
        assertTrue(slnRefs.eResource().getErrors().isEmpty(), "Parsing errors: " + slnRefs.eResource().getErrors());

        // Run T5 generator end-to-end
        SolutionRefGenerator gen = new SolutionRefGenerator();
        InMemoryFileSystemAccess fsa = new InMemoryFileSystemAccess();
        gen.doGenerate(slnRefs.eResource(), fsa, null);

        Map<String, Object> files = fsa.getAllFiles();
        assertFalse(files.isEmpty(), "No files generated by T5");
        assertTrue(files.keySet().stream().anyMatch(n -> n.endsWith("solution.sln")), "Missing solution.sln");
        // Updated to match new MultiFileCppGenerator architecture
        assertTrue(files.keySet().stream().anyMatch(n -> n.endsWith("platform1_engine.cpp")), "Missing platform1_engine.cpp");
        assertTrue(files.keySet().stream().anyMatch(n -> n.endsWith("platform1_state.hpp")), "Missing platform1_state.hpp");
        assertTrue(files.keySet().stream().anyMatch(n -> n.endsWith("orchestrator.cpp")), "Missing orchestrator.cpp");

        // Debug: Print what files were generated
        System.out.println("Generated files:");
        for (String fileName : files.keySet()) {
            System.out.println("  - " + fileName);
        }

        // Persist to temp for inspection and runnable sandbox
        Path outDir = integrationRoot().resolve("default").resolve("temp");
        Files.createDirectories(outDir);
        for (Map.Entry<String, Object> e : files.entrySet()) {
            String name = e.getKey().replace('/', '_');
            Path outputFile = outDir.resolve(name);
            Files.writeString(outputFile, e.getValue().toString());
            System.out.println("Wrote: " + outputFile);
        }

        // Write canonical filenames for convenience (only generated files)
        String platformEngineKey = files.keySet().stream().filter(n -> n.endsWith("platform1_engine.cpp")).findFirst().orElse(null);
        if (platformEngineKey != null) {
            Files.writeString(outDir.resolve("platform1_engine.cpp"), files.get(platformEngineKey).toString());
        }
        String platformStateKey = files.keySet().stream().filter(n -> n.endsWith("platform1_state.hpp")).findFirst().orElse(null);
        if (platformStateKey != null) {
            Files.writeString(outDir.resolve("platform1_state.hpp"), files.get(platformStateKey).toString());
        }
        String orchestratorKey = files.keySet().stream().filter(n -> n.endsWith("orchestrator.cpp")).findFirst().orElse(null);
        if (orchestratorKey != null) {
            Files.writeString(outDir.resolve("orchestrator.cpp"), files.get(orchestratorKey).toString());
        }

        // Note: We don't copy manual files (world.cpp, PickPlace.c, etc.) here
        // This test verifies generator output only. Integration testing is separate.
        // Trivial assertion to force execution
        assertTrue(files.size() > 0);
    }
}
