package circus.robocalc.robosim.physmod.generator.sourceCodeGen.tests;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

import org.eclipse.xtext.generator.InMemoryFileSystemAccess;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;

import com.google.inject.Injector;

import circus.robocalc.robosim.physmod.generator.sourceCodeGen.SolutionRefGenerator;
import circus.robocalc.robosim.physmod.slnRef.SlnRefStandaloneSetup;
import circus.robocalc.robosim.physmod.slnRef.slnRef.SlnRefs;

/**
 * T5 Visual integration test: feed T4 Visual slnRef output and ensure T5 generates visualization code.
 */
public class TestVisual_T5Integration {

    private Path integrationRoot() {
        return Paths.get("").toAbsolutePath().resolve("tests").resolve("integrationTests").resolve("vis");
    }
    
    // Main method to run test directly
    public static void main(String[] args) {
        try {
            TestVisual_T5Integration test = new TestVisual_T5Integration();
            test.testGenerateFromT4SlnRef_Visual();
            System.out.println("✅ Test completed successfully!");
        } catch (Exception e) {
            System.err.println("❌ Test failed: " + e.getMessage());
            e.printStackTrace();
        }
    }

    @Test
    public void testGenerateFromT4SlnRef_Visual() throws Exception {
        // STAGE 2 Input: T4 Visual slnRef (stage2 = slnRef input to T5)
        Path inputStage2 = integrationRoot().resolve("input").resolve("stage2").resolve("VisualExample.slnRef");
        assertTrue(Files.exists(inputStage2), "Missing input slnRef: " + inputStage2);

        String slnRefText = Files.readString(inputStage2);

        // Parse slnRef using its standalone setup
        Injector inj = new SlnRefStandaloneSetup().createInjectorAndDoEMFRegistration();
        @SuppressWarnings("unchecked")
        ParseHelper<SlnRefs> parseHelper = inj.getInstance(ParseHelper.class);
        SlnRefs slnRefs = parseHelper.parse(slnRefText);
        assertNotNull(slnRefs, "Failed to parse SlnRefs");
        assertTrue(slnRefs.eResource().getErrors().isEmpty(), "Parsing errors: " + slnRefs.eResource().getErrors());

        // Set system properties for solution name, visualization, and generation mode
        String originalSolutionName = System.getProperty("physmod.solution.name");
        String originalVisual = System.getProperty("physmod.visualisation.enabled");
        String originalMode = System.getProperty("physmod.generation.mode");
        try {
            System.setProperty("physmod.solution.name", "physics_standalone_visual");
            System.setProperty("physmod.visualisation.enabled", "true");
            System.setProperty("physmod.generation.mode", "STANDALONE_VISUALISATION");
            
            // Run T5 generator end-to-end
            SolutionRefGenerator gen = new SolutionRefGenerator();
            InMemoryFileSystemAccess fsa = new InMemoryFileSystemAccess();
            gen.doGenerate(slnRefs.eResource(), fsa, null);

            Map<String, Object> files = fsa.getAllFiles();
            assertFalse(files.isEmpty(), "No files generated by T5");

            // Helper to strip output configuration prefix from file keys
            java.util.function.Function<String, String> stripPrefix = (key) -> {
                if (key.contains(":")) {
                    return key.split(":", 2)[1];
                } else if (key.startsWith("DEFAULT_OUTPUT")) {
                    return key.substring("DEFAULT_OUTPUT".length());
                }
                return key;
            };

            // Verify expected files are generated (accounting for DEFAULT_OUTPUT prefix)
            assertTrue(files.keySet().stream().anyMatch(n -> stripPrefix.apply(n).endsWith("solution.sln")),
                "Missing solution.sln. Generated files: " + files.keySet());
            assertTrue(files.keySet().stream().anyMatch(n -> stripPrefix.apply(n).endsWith("platform1_engine.cpp")), 
                "Missing platform1_engine.cpp. Generated files: " + files.keySet());
            assertTrue(files.keySet().stream().anyMatch(n -> stripPrefix.apply(n).endsWith("platform1_state.hpp")), 
                "Missing platform1_state.hpp. Generated files: " + files.keySet());
            assertTrue(files.keySet().stream().anyMatch(n -> stripPrefix.apply(n).equals("CMakeLists.txt") || stripPrefix.apply(n).endsWith("/CMakeLists.txt")), 
                "Missing CMakeLists.txt. Generated files: " + files.keySet());
            assertTrue(files.keySet().stream().anyMatch(n -> stripPrefix.apply(n).startsWith("src/")), 
                "Missing src/ directory files. Generated files: " + files.keySet());

            // Debug: Print what files were generated
            System.out.println("Generated Visual files:");
            for (String fileName : files.keySet()) {
                System.out.println("  - " + fileName);
            }

            // STAGE 1: Persist Solution DSL (.sln) to temp/stage1
            Path tempStage1 = integrationRoot().resolve("temp").resolve("stage1");
            Files.createDirectories(tempStage1);
            for (Map.Entry<String, Object> e : files.entrySet()) {
                if (e.getKey().endsWith(".sln")) {
                    String name = e.getKey().replace('/', '_');
                    Path outputFile = tempStage1.resolve(name);
                    Files.writeString(outputFile, e.getValue().toString());
                    System.out.println("Wrote Stage1 output: " + outputFile);
                }
            }

            // STAGE 2: Persist C++ code to temp/stage2
            Path tempStage2 = integrationRoot().resolve("temp").resolve("stage2");
            Files.createDirectories(tempStage2);
            for (Map.Entry<String, Object> e : files.entrySet()) {
                if (!e.getKey().endsWith(".sln")) {
                    // Extract file path: remove output configuration prefix (e.g., "DEFAULT_OUTPUT")
                    String filePath = e.getKey();
                    // InMemoryFileSystemAccess may prepend output config name - remove it
                    // Format can be "DEFAULT_OUTPUT:path" or "DEFAULT_OUTPUTpath"
                    if (filePath.contains(":")) {
                        String[] parts = filePath.split(":", 2);
                        filePath = parts[1]; // Use path after output config and colon
                    } else if (filePath.startsWith("DEFAULT_OUTPUT")) {
                        filePath = filePath.substring("DEFAULT_OUTPUT".length());
                    }
                    
                    // Preserve directory structure (e.g., "src/platform1_engine.cpp" or "CMakeLists.txt")
                    Path outputFile = tempStage2.resolve(filePath);
                    if (outputFile.getParent() != null) {
                        Files.createDirectories(outputFile.getParent());
                    }
                    Files.writeString(outputFile, e.getValue().toString());
                    System.out.println("Wrote Stage2 output: " + outputFile + " (from key: " + e.getKey() + ")");
                }
            }

            assertTrue(files.size() > 0);
        } finally {
            // Restore original system properties
            if (originalSolutionName != null) {
                System.setProperty("physmod.solution.name", originalSolutionName);
            } else {
                System.clearProperty("physmod.solution.name");
            }
            if (originalVisual != null) {
                System.setProperty("physmod.visualisation.enabled", originalVisual);
            } else {
                System.clearProperty("physmod.visualisation.enabled");
            }
            if (originalMode != null) {
                System.setProperty("physmod.generation.mode", originalMode);
            } else {
                System.clearProperty("physmod.generation.mode");
            }
        }
    }
}