/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SlnRefProposalProvider extends AbstractSlnRefProposalProvider {
}
