/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SlnRefUiModule extends AbstractSlnRefUiModule {

	public SlnRefUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
