source.. = src/,\
           xtend-gen/,\
           lib/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               templates/
bin.excludes = **/*.xtend
src.includes = \
               icons/,\
               templates/
