/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.robosim.physmod.slnDF.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import circus.robocalc.robosim.physmod.slnDF.SlnDFRuntimeModule;
import circus.robocalc.robosim.physmod.slnDF.SlnDFStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SlnDFIdeSetup extends SlnDFStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SlnDFRuntimeModule(), new SlnDFIdeModule()));
	}
	
}
