/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.robosim.physmod.slnDF.ide;


/**
 * Use this class to register ide components.
 */
public class SlnDFIdeModule extends AbstractSlnDFIdeModule {
}
