package circus.robocalc.robosim.physmod.generator.sourceCodeGen.tests.RobotExamples.ClosedChain;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

import org.eclipse.xtext.generator.InMemoryFileSystemAccess;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import com.google.inject.Inject;
import com.google.inject.Injector;

import circus.robocalc.robosim.physmod.generator.sourceCodeGen.MultiFileCppGenerator;
import circus.robocalc.robosim.physmod.generator.sourceCodeGen.SolutionRefGenerator;
import circus.robocalc.robosim.physmod.generator.sourceCodeGen.tests.SlnDFInjectorProvider;
import circus.robocalc.robosim.physmod.generator.sourceCodeGen.tests.SlnRefInjectorProvider;
import circus.robocalc.robosim.physmod.slnRef.slnRef.SlnRefs;
import circus.robocalc.robosim.physmod.slnDF.slnDF.Solution;

@ExtendWith(InjectionExtension.class)
@InjectWith(SlnRefInjectorProvider.class)
public class FourBarClosedChainSourceCodeGenTest {

    @Inject
    private ParseHelper<SlnRefs> slnRefParseHelper;

    private ParseHelper<Solution> solutionDSLParseHelper;

    private ParseHelper<Solution> getSolutionDSLParseHelper() {
        if (solutionDSLParseHelper == null) {
            SlnDFInjectorProvider provider = new SlnDFInjectorProvider();
            Injector injector = provider.getInjector();
            solutionDSLParseHelper = injector.getInstance(ParseHelper.class);
        }
        return solutionDSLParseHelper;
    }

    @Test
    void testClosedChainSlnRefGeneratesSolutionDsl() throws Exception {
        Path input = resolveSlnRefInput();
        String slnRefText = Files.readString(input, StandardCharsets.UTF_8);

        SlnRefs slnRefs = slnRefParseHelper.parse(slnRefText);
        assertNotNull(slnRefs, "Failed to parse SlnRefs");
        assertTrue(slnRefs.eResource().getErrors().isEmpty(),
            () -> "SlnRef parse errors: " + slnRefs.eResource().getErrors());

        SolutionRefGenerator generator = new SolutionRefGenerator();
        String solutionDSL = generator.compile(slnRefs);
        assertNotNull(solutionDSL, "Generated Solution DSL is null");
        assertFalse(solutionDSL.trim().isEmpty(), "Generated Solution DSL is empty");

        assertTrue(solutionDSL.contains("G_c = Q_c * B_sel * transpose(phi) * transpose(H);"),
            "Missing ConstraintJacobian computation for G_c");
        assertTrue(solutionDSL.contains("Uprime = - Q_c * B_sel * transpose(phi) * a;"),
            "Missing ConstraintJacobian computation for Uprime");
        assertTrue(solutionDSL.contains("lambda_c"),
            "Missing lambda_c definition in constrained dynamics");
        assertTrue(solutionDSL.contains("dd_theta = dd_theta_0 + (M_inv * transpose(G_c) * lambda_c);"),
            "Missing constrained acceleration computation");

        Solution solution = getSolutionDSLParseHelper().parse(solutionDSL);
        assertNotNull(solution, "Generated Solution DSL failed to parse");
        assertTrue(solution.eResource().getErrors().isEmpty(),
            () -> "Solution DSL parse errors: " + solution.eResource().getErrors());

        MultiFileCppGenerator cppGen = new MultiFileCppGenerator();
        InMemoryFileSystemAccess fsa = new InMemoryFileSystemAccess();
        cppGen.doGenerate(solution.eResource(), fsa, null);

        Map<String, Object> files = fsa.getAllFiles();
        assertFalse(files.isEmpty(), "No files generated by T5 source code generator");

        boolean foundLambda = files.values().stream()
            .map(Object::toString)
            .anyMatch(content -> content.contains("lambda_c"));
        assertTrue(foundLambda, "Generated C++ should include lambda_c for constrained dynamics");
    }

    private static Path resolveSlnRefInput() throws IOException {
        Path cwd = Paths.get("").toAbsolutePath();
        Path rel = Paths.get(
            "physmod-testdata",
            "circus.robocalc.robosim.physmod.testdata",
            "testdata",
            "integration",
            "T5",
            "ClosedChain",
            "SKO",
            "input",
            "FourBarPlanarLinkage.slnRef"
        );

        List<Path> candidates = List.of(
            cwd.resolve(rel),
            cwd.resolve("..").resolve(rel),
            cwd.resolve("..").resolve("..").resolve(rel)
        );

        for (Path candidate : candidates) {
            if (Files.exists(candidate)) {
                return candidate.normalize();
            }
        }

        throw new IOException("FourBarPlanarLinkage.slnRef not found. Tried: " + candidates);
    }
}
