/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.robosim.physmod.slnDF;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SlnDFRuntimeModule extends AbstractSlnDFRuntimeModule {
}
