/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.robosim.physmod.slnDF;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SlnDFStandaloneSetup extends SlnDFStandaloneSetupGenerated {

	public static void doSetup() {
		new SlnDFStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
