/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnRef.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SlnRefValidator extends AbstractSlnRefValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					SlnRefPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
