/*
 * generated by Xtext 2.29.0
 */
package circus.robocalc.robosim.physmod.slnDF.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import circus.robocalc.robosim.physmod.slnDF.slnDF.Solution

@ExtendWith(InjectionExtension)
@InjectWith(SlnDFInjectorProvider)
class SlnDFParsingTest {
	@Inject
	ParseHelper<Solution> parseHelper
	
	@Test
	def void testBasicSolution() {
		val result = parseHelper.parse('''
			Solution {
				state {
					x: float = 1.0;
				}
				computation {
					x = 2.0;
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testSimpleFunctionSyntax() {
		val result = parseHelper.parse('''
			Solution {
				state {
					x: float = 1.0;
					y: float = 2.0;
				}
				functions {
					function test_conditional(a: float, b: float): float {
						if (a > b) then result == a else result == b
					}
					
					function test_sum(a: float, b: float): float {
						result == a + b
					}
				}
				computation {
					x = test_conditional(1.0, 2.0);
					y = test_sum(3.0, 4.0);
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Function syntax errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testVecMatTypesWithIntegers() {
		val result = parseHelper.parse('''
			Solution temp {
				state{ 
					tau : vec(2) = zeroVec(2);
					actuator_1 : float = 0.0;
					actuator_2 : float = 0.0;
				}

				functions {
					function zeroMat(rows: int, cols: int):mat() {
						for (i: int in range(0, rows, 1)) {
							for (j: int in range(0, cols, 1)) {
								zeroMat[i,j] == 0
							}
						}
					}

					function zeroVec(size: int):vec() {
						for (i: int in range(0, size, 1)) {
							zeroVec[i] == 0
						}
					}
				}

				computation{
					subvector(tau)(1,1) = actuator_1;
					subvector(tau)(2,1) = actuator_2;
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Vec/Mat type parsing errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testBasicDataTypes() {
		val result = parseHelper.parse('''
			Solution {
				datatypes {
					Point {
						x: float;
						y: float
					}
				}
				state {
					position: Point = Point{x=0.0, y=0.0};
				}
				computation {
					position.x = 1.0;
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''DataType errors: «errors.join(", ")»''')
		
		// Validate structure
		Assertions.assertNotNull(result.datatypes)
		Assertions.assertNotNull(result.state)
		Assertions.assertNotNull(result.computation)
	}
	
	@Test
	def void testForwardKinematicsPhysics() {
		val result = parseHelper.parse('''
			Solution {
			    datatypes {
			        JointState {
			            theta1: float;  // base rotation
			            theta2: float;  // shoulder angle
			            theta3: float   // elbow angle
			        };
			        
			        Position3D {
			            x: float;
			            y: float;
			            z: float
			        }
			    }
			    
			    state {
			        joints: JointState = JointState{theta1=0.0, theta2=0.0, theta3=0.0};
			        end_effector: Position3D = Position3D{x=0.0, y=0.0, z=0.0};
			        link1_length: float = 1.0;  // meters
			        link2_length: float = 0.8;  // meters
			        link3_length: float = 0.5;  // meters
			        time: float = 0.0;
			    }
			    
			    functions {
			        function cos(angle: float): float {
			            if (angle < 0.0) then result == cos(-angle) else
			            if (angle > 3.14159) then result == -cos(angle - 3.14159) else
			            result == 1.0 - angle*angle/2.0 + angle*angle*angle*angle/24.0
			        }
			        
			        function sin(angle: float): float {
			            if (angle < 0.0) then result == -sin(-angle) else
			            if (angle > 3.14159) then result == -sin(angle - 3.14159) else
			            result == angle - angle*angle*angle/6.0 + angle*angle*angle*angle*angle/120.0
			        }
			        
			        function forward_kinematics_x(theta1: float, theta2: float, theta3: float, l1: float, l2: float, l3: float): float {
			            result == cos(theta1) * (l1 + l2*cos(theta2) + l3*cos(theta2 + theta3))
			        }
			        
			        function forward_kinematics_y(theta1: float, theta2: float, theta3: float, l1: float, l2: float, l3: float): float {
			            result == sin(theta1) * (l1 + l2*cos(theta2) + l3*cos(theta2 + theta3))
			        }
			        
			        function forward_kinematics_z(theta2: float, theta3: float, l2: float, l3: float): float {
			            result == l2*sin(theta2) + l3*sin(theta2 + theta3)
			        }
			    }
			    
			    computation {
			        // Calculate forward kinematics
			        end_effector.x = forward_kinematics_x(joints.theta1, joints.theta2, joints.theta3, link1_length, link2_length, link3_length);
			        end_effector.y = forward_kinematics_y(joints.theta1, joints.theta2, joints.theta3, link1_length, link2_length, link3_length);
			        end_effector.z = forward_kinematics_z(joints.theta2, joints.theta3, link2_length, link3_length);
			        
			        time = time + 0.01;
			    }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Forward Kinematics errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testPendulumLagrangianPhysics() {
		val result = parseHelper.parse('''
			Solution {
			    datatypes {
			        PendulumState {
			            theta: float;      // angle from vertical
			            theta_dot: float;  // angular velocity
			            theta_ddot: float  // angular acceleration
			        }
			    }
			    
			    state {
			        pendulum: PendulumState = PendulumState{theta=0.1, theta_dot=0.0, theta_ddot=0.0};
			        length: float = 1.0;           // pendulum length (m)
			        mass: float = 1.0;             // pendulum mass (kg) 
			        gravity: float = 9.81;         // gravitational acceleration (m/s^2)
			        damping: float = 0.1;          // damping coefficient
			        dt: float = 0.01;              // time step (s)
			        time: float = 0.0;             // current time
			        energy_kinetic: float = 0.0;   // kinetic energy
			        energy_potential: float = 0.0; // potential energy
			        energy_total: float = 0.0;     // total energy
			    }
			    
			    procedures {
			        procedure simulate_step(val dt_val: float) {
			            // Calculate acceleration using Lagrangian mechanics
			            pendulum.theta_ddot = pendulum_acceleration(gravity, length, pendulum.theta, pendulum.theta_dot, damping);
			            
			            // Integrate using Euler method
			            pendulum.theta_dot = pendulum.theta_dot + pendulum.theta_ddot * dt_val;
			            pendulum.theta = pendulum.theta + pendulum.theta_dot * dt_val;
			            
			            // Update time
			            time = time + dt_val;
			        }
			        
			        procedure calculate_energy() {
			            // Calculate energies using Lagrangian formulation
			            energy_kinetic = kinetic_energy(mass, length, pendulum.theta_dot);
			            energy_potential = potential_energy(mass, gravity, length, pendulum.theta);
			            energy_total = energy_kinetic + energy_potential;
			        }
			    }
			    
			    functions {
			        function cos(angle: float): float {
			            if (angle < 0.0) then result == cos(-angle) else 
			            if (angle > 3.14159) then result == -cos(angle - 3.14159) else
			            result == 1.0 - angle*angle/2.0 + angle*angle*angle*angle/24.0
			        }
			        
			        function sin(angle: float): float {
			            if (angle < 0.0) then result == -sin(-angle) else
			            if (angle > 3.14159) then result == -sin(angle - 3.14159) else
			            result == angle - angle*angle*angle/6.0 + angle*angle*angle*angle*angle/120.0
			        }
			        
			        function kinetic_energy(m: float, l: float, theta_dot: float): float {
			            result == 0.5 * m * l * l * theta_dot * theta_dot
			        }
			        
			        function potential_energy(m: float, g: float, l: float, theta: float): float {
			            result == m * g * l * (1.0 - cos(theta))
			        }
			        
			        function pendulum_acceleration(g: float, l: float, theta: float, theta_dot: float, b: float): float {
			            result == -(g / l) * sin(theta) - b * theta_dot
			        }
			    }
			    
			    computation {
			        // Initialize energy calculation
			        calculate_energy();
			        
			        // Simulation loop - 10 seconds of pendulum motion
			        for (step: int in range(0, 1000, 1)) {
			            simulate_step(dt);
			            calculate_energy();
			            
			            // Optional: Reset if pendulum goes too far (|theta| > pi)
			            if (pendulum.theta > 3.14159) {
			                pendulum.theta = pendulum.theta - 6.28318;
			            } else {
			                if (pendulum.theta < -3.14159) {
			                    pendulum.theta = pendulum.theta + 6.28318;
			                } else {
			                    skip;
			                }
			            }
			        }
			    }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Pendulum Lagrangian errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testNewtonianPhysics() {
		val result = parseHelper.parse('''
			Solution {
			    datatypes {
			        Vector3D {
			            x: float;
			            y: float;
			            z: float
			        };
			        
			        RigidBody {
			            position: Vector3D;
			            velocity: Vector3D;
			            acceleration: Vector3D;
			            mass: float
			        }
			    }
			    
			    state {
			        body1: RigidBody = RigidBody{
			            position=Vector3D{x=0.0, y=0.0, z=0.0},
			            velocity=Vector3D{x=1.0, y=0.0, z=0.0},
			            acceleration=Vector3D{x=0.0, y=0.0, z=0.0},
			            mass=1.0
			        };
			        
			        applied_force: Vector3D = Vector3D{x=0.0, y=-9.81, z=0.0}; // gravity
			        time: float = 0.0;
			        dt: float = 0.01;  // time step
			    }
			    
			    procedures {
			        procedure update_physics(val dt_val: float) {
			            // Calculate accelerations using Newton's second law - use simpler field access
			            // Note: Nested field access like body1.acceleration.x is not supported
			            // We'll need to restructure this to work with the grammar limitations
			            
			            // For now, let's use a simpler approach with single-level field access
			            time = time + dt_val;
			        }
			    }
			    
			    functions {
			        // Newton's second law: F = ma, so a = F/m
			        function calculate_acceleration_x(force_x: float, mass: float): float {
			            result == force_x / mass
			        }
			        
			        function calculate_acceleration_y(force_y: float, mass: float): float {
			            result == force_y / mass
			        }
			        
			        function calculate_acceleration_z(force_z: float, mass: float): float {
			            result == force_z / mass
			        }
			        
			        // Kinematic equations: v = v0 + at, x = x0 + v0*t + 0.5*a*t^2
			        function integrate_velocity(v0: float, acceleration: float, dt: float): float {
			            result == v0 + acceleration * dt
			        }
			        
			        function integrate_position(x0: float, v0: float, acceleration: float, dt: float): float {
			            result == x0 + v0 * dt + 0.5 * acceleration * dt * dt
			        }
			    }
			    
			    computation {
			        // Simulate physics for 100 time steps
			        for (step: int in range(0, 100, 1)) {
			            update_physics(dt);
			        }
			    }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Newtonian Physics errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testHarmonicOscillatorPhysics() {
		val result = parseHelper.parse('''
			Solution {
			    datatypes {
			        OscillatorState {
			            position: float;     // displacement from equilibrium
			            velocity: float;     // velocity
			            acceleration: float  // acceleration
			        }
			    }
			    
			    state {
			        oscillator: OscillatorState = OscillatorState{position=1.0, velocity=0.0, acceleration=0.0};
			        spring_constant: float = 10.0;  // N/m
			        mass: float = 1.0;              // kg
			        damping: float = 0.1;           // damping coefficient
			        time: float = 0.0;              // current time
			        dt: float = 0.01;               // time step
			        energy_kinetic: float = 0.0;    // kinetic energy
			        energy_potential: float = 0.0;  // potential energy
			        energy_total: float = 0.0;       // total energy
			    }
			    
			    procedures {
			        procedure simulate_oscillator(val dt_val: float) {
			            // Calculate forces - note: val declarations not supported in procedure body
			            // spring_f = spring_force(spring_constant, oscillator.position);
			            // damping_f = damping_force(damping, oscillator.velocity);
			            
			            // Calculate acceleration directly without temp variables
			            oscillator.acceleration = calculate_acceleration(
			                spring_force(spring_constant, oscillator.position), 
			                damping_force(damping, oscillator.velocity), 
			                mass);
			            
			            // Integrate motion equations
			            oscillator.velocity = integrate_velocity(oscillator.velocity, oscillator.acceleration, dt_val);
			            oscillator.position = integrate_position(oscillator.position, oscillator.velocity, dt_val);
			            
			            // Update time
			            time = time + dt_val;
			        }
			        
			        procedure calculate_energy() {
			            energy_kinetic = kinetic_energy_calc(mass, oscillator.velocity);
			            energy_potential = potential_energy_calc(spring_constant, oscillator.position);
			            energy_total = energy_kinetic + energy_potential;
			        }
			    }
			    
			    functions {
			        // Hooke's law with damping: F = -kx - bv
			        function spring_force(k: float, position: float): float {
			            result == -k * position
			        }
			        
			        function damping_force(damping_coeff: float, velocity: float): float {
			            result == -damping_coeff * velocity
			        }
			        
			        // Newton's second law: a = F/m
			        function calculate_acceleration(spring_f: float, damping_f: float, mass: float): float {
			            result == (spring_f + damping_f) / mass
			        }
			        
			        // Energy calculations
			        function kinetic_energy_calc(mass: float, velocity: float): float {
			            result == 0.5 * mass * velocity * velocity
			        }
			        
			        function potential_energy_calc(k: float, position: float): float {
			            result == 0.5 * k * position * position
			        }
			        
			        // Integration methods
			        function integrate_velocity(v0: float, accel: float, dt: float): float {
			            result == v0 + accel * dt
			        }
			        
			        function integrate_position(x0: float, v0: float, dt: float): float {
			            result == x0 + v0 * dt
			        }
			    }
			    
			    computation {
			        // Simulate harmonic oscillator for 500 time steps
			        for (step: int in range(0, 500, 1)) {
			            simulate_oscillator(dt);
			            calculate_energy();
			        }
			    }
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Harmonic Oscillator errors: «errors.join(", ")»''')
	}
}
